spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: root
  jpa:
   hibernate:
    ddl-auto: update
  application:
    name: coupon-service
server:
  port: 8082 
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultzone: http://localhost:8761/eureka
    
      
    
  

    

  

    
 