
server:
  port: 8082


management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
      base-path: /myactuator
      
      
  info:
    env:
      enabled: true

 
  
logging:
  level:
    com:
     zensar: debug
  
        