spring:
  datasource:
    url: jdbc:mysql://localhost:3306/javabatch
    password: root
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
       # dialect: org.hibernate.dialect.MySQLDialect
       
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
        exclude:
        - beans
        
      base-path: /modifiedactuator
      
  info:
    build:
      enabled: true
    git:
      enabled: true
    env:
      enabled: true
   # created by: jagadeesh
        
  endpoint:
    shutdown:
      enabled: true 
      
logging:
  level:
    com:
    zensar: debug
       
      
      
 
        
      