spring:
  datasource:
    url: jdbc:mysql://localhost:3306/javabatch
    password: root
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
       # dialect: org.hibernate.dialect.MySQLDialect
  application:
    name: coupen-service
       
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
        exclude:
        - beans
        
      base-path: /newactuator
      
  info:
    build:
      enabled: true
    git:
      enabled: true
    env:
      enabled: true
   # created by: jagadeesh
        
  endpoint:
    shutdown:
      enabled: true 
      
logging:
  level:
    com:
    zensar: debug
    
server:
  port: 8082
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      deafultzone: http://localhost:8761/eureka
  
 
       
      
      
 
        
      